### ISSUE TITLE
Ellis numbers malformed

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/clearwater-heat#13]
After spinning up Clearwater using the Heat templates, the Ellis numbers table can been populated with entries of the form `<number>@` - ie. no domain name.

The problem is caused by a race condition that can result in local_settings.py not being updated before the create_numbers.py script runs.

The relevant section from the template is

            # Configure and upload /etc/clearwater/shared_config.
            cat > /etc/clearwater/shared_config << EOF
            …
            EOF
            sudo /usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
            sudo /usr/share/clearwater/clearwater-config-manager/scripts/apply_shared_config

            # Allocate a allocate a pool of numbers to assign to users.
            /usr/share/clearwater/ellis/env/bin/python /usr/share/clearwater/ellis/src/metaswitch/ellis/tools/create_numbers.py --start __dn_range_start__ --count __dn_range_length__

Because apply_shared_config isn’t synchronous, it is possible for the create_numbers job to run before the /usr/share/clearwater/infrastructure/scripts/ellis script has run and updated local_settings.py.

In the short term adding "sudo service clearwater-infrastructure restart" after the shared_config file has been written fixes the problem, but longer term it would be best to have a way of forcing apply_shared_config to complete synchronously.

**Comment by mirw** [comment]
See https://github.com/Metaswitch/clearwater-etcd/issues/129 for the etcd issue to add a way of waiting for apply_shared_config to complete..
