### ISSUE TITLE
Repo issue

### ISSUE THREAD

**Issue by cargreg** [Metaswitch/clearwater-heat#17]
I guys , 
I have encounter a problem with the repository , when i try to launch the apt-get update command after add repo with the command  echo deb http://repo.cw-ngv.com/stable/binary > /etc/apt/sources.list.d/clearwater.list , apt returm me 
E: La riga 1 nel file /etc/apt/sources.list.d/clearwater.list non è corretta (dist)
E: Impossibile leggere l'elenco dei sorgenti.
The row 1 in the file /etc/apt/sources.list.d/clearwater.list doesn't correct
Impossible read the source list

Hi , Carmine

**Comment by eleanor-merry** [comment]
Hi @cargreg. Our repository server was down temporarily, but we've now fixed this up. Can you please try this again?

**Comment by cargreg** [comment]
Eleanor thanks for the answer , today try again to launch the stack

**Comment by rkd-msw** [comment]
@cargreg - as there hasn't been an update for a while, I'm going to close this. Let us know if you are still having this problem, and I'll reopen it.
