### ISSUE TITLE
Heat stack-create fails with "dns: private_net_id Must be a valid network ID"

### ISSUE THREAD

**Issue by keesjank** [Metaswitch/clearwater-heat#18]
Hi,

I’m trying to deploy Clearwater through the heat templates. The Openstack I’m using is the Autopilot one from Ubuntu. Heat is not included but was added to the deployment through `juju`. It seems to be running ok; I can run a simple template that adds a network and a subnet successfully for instance.

But if I run the `clearwater.yaml` template, it fails on the stack create:

`ubuntu@blade01:~/clearwater-heat-master$ heat stack-create -f clearwater-https.yaml -P "public_net_id=0e8f6492-d89a-46fb-8317-c4a7eafe8f21;dnssec_key=iUGIfN2z9sniRHOPTgxARFt6oK7bbAgKnIJQQZV0qkrWWZ4RmCo+C4wB8i8ijfzWJ1DpB2D2QGkTG1f4ntdUAw==;image=ubuntu-14.04-server-cloudimg-amd64-disk1;key_name=kedo-keys;flavor=m1.small" clearwater
ERROR: Property error : dns: private_net_id Must be a valid network ID
ubuntu@blade01:~/clearwater-heat-master$`

Btw I had to rewrite `clearwater.yaml` to point to the webpages at github (`type: https://raw.githubusercontent.com/Metaswitch/clearwater-heat/master/network.yaml`), because I couldn’t get the local files to work (allowed-schemes error).

I am not sure there is debugging on the processing of a template, but there is api debugging so I attached that in a file: [heat-clearwater-fail-private-net.txt](https://github.com/Metaswitch/clearwater-heat/files/70958/heat-clearwater-fail-private-net.txt)

Any ideas for further troubleshooting?

**Comment by eleanor-merry** [comment]
Hi @keesjank. What version of Heat are you using? We've seen the allowed-schemes error before on an older version of Heat.

**Comment by keesjank** [comment]
Hi Eleanor,

Thanks for the reply. You are right. I assumed that Ubuntu 14.04 LTS and
it's juju charm for heat would be up to date or at least quite recent, but
it turns out it contains the 0.2.8 version, which is I think 2 years old
now? So I tried to upgrade the charm, but it says it is the current one. It
hadn't crossed my mind to see if there were special juju deploy parameters
that would trigger an install of a more recent heat version, so I deleted
the complete openstack install, hoping to get a more recent heat with the
'manual' install described at:
http://docs.openstack.org/liberty/install-guide-ubuntu/.

That makes me think, do you have a favorite openstack deployment?

2016-01-04 13:51 GMT+01:00 Eleanor Merry <notifications@github.com>:

**Comment by keesjank** [comment]
I have the OpenStack install at http://docs.openstack.org/liberty/install-guide-ubuntu/ running now. It is using heat client 0.8.0 and engine 5.0.0, so the allowed-schemes problem is gone. Unfortunately the heat stack creation fails:

    ubuntu@blade01:~/clearwater-heat-master$ heat stack-create clearwater -f clearwater.yaml -P "public_net_id=4ca6f259-9e24-4cb3-ba5b-3c00a668dc28;dnssec_key=<edited>;image=69df2460-7fa3-4cf6-bc3f-0d0e107863c3;flavor=m1.clearwater;key_name=kedo"
    ERROR: Failed to validate: : resources.dns: : At least one of the following properties must be specified: network, network_id
    ubuntu@blade01:~/clearwater-heat-master$

Here is the heat engine debug output. It seems to stop at the port validation in dns.yaml. [heat.engine.debug.txt](https://github.com/Metaswitch/clearwater-heat/files/78312/heat.engine.debug.txt)

Probably I'm hitting this bug: https://bugs.launchpad.net/heat/+bug/1407392. It should be fixed in Juno/Kilo, but I'm not sure about Liberty.

**Comment by antongulenko** [comment]
Hello,
I am currently facing the exact same issue you described in your comment. It originates from validating the port resource `sig_port` in `dns.yaml`. The error is thrown even though the `network_id` (or `network`) property is there.
The bug persists even though I upgraded heat-engine to 5.0.1 (Liberty). [This bug](https://bugs.launchpad.net/heat/+bug/1518676) suggested it might be fixed in 5.0.1.
Did you maybe find a workaround for this bug?
The last comment in [the bug you found](https://bugs.launchpad.net/heat/+bug/1407392) indicates a workaround which I don't understand:
> If the parameters passed from one nested stack to the other, the value for that parameter ("network") should be set before.
Otherwise the Port validation does not see it and then an exception will be thrown.

Cheers,
Anton

**Comment by keesjank** [comment]
Hi Anton,

No I didn't pursue this path any further. Just waiting for a new heat
package to appear and then i'll try again.

Instead I tried OPNFV on another bunch of servers. The heat version in
OPNFV is older (0.2.12), but at least the stack gets accepted and deployed.
But unfortunately it never gets further than that. The bash scripts in the
heat templates do not run for some reason, so you get the instances, but
clearwater doesn't install. I tried to run those scripts manually. No
success. Waiting for fixes here too.

Next challenge is RDO with RDO Manager.

I think the text you are referring to is not really describing a workaround
but how the fix should be implemented.

Keesjan.

2016-02-01 18:08 GMT+01:00 Anton Gulenko <notifications@github.com>:

**Comment by rkd-msw** [comment]
I hit this issue after upgrading to OpenStack Liberty and Heat 0.8.0. I was able to get my stack created by using "network" and a network name, instead of "network_id" and the UUID.

That's at https://github.com/Metaswitch/clearwater-heat/compare/openstack_liberty - unfortunately I couldn't figure out how to plumb the right name through, so I've just hardcoded the name. This should work as long as the stack is called clearwater1.

**Comment by keesjank** [comment]
Thanks, good to know.

BTW Where I mentioned before that OPNFV did not work; after an upgrade it did. The Clearwater heat templates built completely and I had a working Clearwater GUI.

**Comment by mirw** [comment]
It looks like OpenStack Liberty objects to being passed a reference to an OS::Neutron::Net when it actually wants a string containing an id of an OS::Neutron::Net.  In many cases, an OS::Neutron::Net is implicitly cast to a string containing its id, and I guess that's how it worked in the past.  However, around the Kilo/Liberty time frame, there was apparently work done to make network lookup more flexible, accepting names as well as IDs, and I suspect that's responsible for this change.


Unfortunately, I don't believe there's a way of getting the id from an OS::Neutron::Net - at least, there's no attribute or property defined for this.  However, in a truly hideous hack, you can force OpenStack to cast the OS::Neutron::Net to a string by doing a null string replacement, i.e. changing

```
network_id: { get_param: private_mgmt_net_id }
```

to

```
network_id: { str_replace: { params: { x: { get_param: private_mgmt_net_id } }, template: x } }
```

With this, I can successfully use these templates on OpenStack Liberty.  It *should* also be backwards compatible with earlier releases, although I don't have a rig to test on.

Pull request to follow shortly...

**Comment by mirw** [comment]
I think this is now fixed.  Please shout if you still see it.
