### ISSUE TITLE
Homestead node takes 15 minutes to come up

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/clearwater-heat#28]
#### Symptoms

I created a Heat deployment. My Homestead node wasn't ready for ~15 minutes. From the attached log, that was because it spent ages trying and failing to connect to Cassandra - there are 484 instances of the log "nc: connect to 127.0.0.1 port 9160 (tcp) failed: Connection refused".

[clearwater-heat-homestead.txt](https://github.com/Metaswitch/clearwater-heat/files/291632/clearwater-heat-homestead.txt)

#### Impact

Bad user experience - Heat orchestration isn't very fast.

#### Release and environment 

Farfetch'd (release-99) on OpenStack Liberty.

#### Steps to reproduce

Create a Heat stack and wait for Homestead to be usable.

**Comment by mirw** [comment]
I've reproduced this.  The key issue is that

*   we install homestead and homestead-prov before clearwater-managment
*   clearwater-management includes clearwater-etcd, which is the only way we'll get an `/etc/cassandra/cassandra.yaml` file
*   so without clearwater-management, Cassandra won't start
*   both homestead and homestead-prov install schema scripts below `/usr/share/clearwater/cassandra-schemas/`, and these are run by scripts below `/usr/share/clearwater/infrastructure/scripts/` on every `service clearwater-infrastructure restart`
*   these schema scripts wait ~3 minutes (120 cycles of a test that runs a java process plus 1s wait) each
*   we run `service clearwater-infrastructure restart` twice during an install, and each time it waits 3 minutes twice (once for homestead and once for homestead-prov).

The fix looks pretty simple - we can simply drop out of the schema install script if `/etc/cassandra/cassandra.yaml` doesn't exist - if we're not using clearwater-management, this configuration should already exist and if we are using clearwater-management, clearwater-cluster-manager will call the schema install script again once `/etc/cassandra/cassandra.yaml` has been created.

I'll test this out tomorrow.

**Comment by rkd-msw** [comment]
We should already be dropping out of the install script if there's no cassandra.yaml - https://github.com/Metaswitch/clearwater-cassandra/blob/master/clearwater-cassandra/usr/share/clearwater/cassandra_schema_utils.sh#L66 and https://github.com/Metaswitch/homestead/blob/dev/homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh#L6. I wonder why that's not working?

**Comment by mirw** [comment]
It seems that there is already an `/etc/cassandra/cassandra.yaml` file put in place by the cassandra package.  However, we haven't yet installed the `/etc/monit/conf.d/cassandra.monit` script, so we're not even attempting to start Cassandra.  I wonder if we should look for the presence of cassandra.monit too?  I need to check this wouldn't cause problems on something like Docker (which might not use monit - I can't remember).

**Comment by mirw** [comment]
OK, the simplest fix is actually just to check for clearwater-cassandra to be installed (rather than just cassandra).  This works because clearwater-cassandra removes `/etc/cassandra/cassandra.yaml` as part of its installation process.
