### ISSUE TITLE
what should I set with the parameter "public_sig_net_id" ?

### ISSUE THREAD

**Issue by EggyCheng** [Metaswitch/clearwater-heat#35]
create the stack by running heat stack-create clearwater -f clearwater.yaml -P "public_mgmt_net_id=...;public_sig_net_id=...;dnssec_key=..."

I don't know what I should set with the paramater "public_sig_net_id".
I already know the "public_mgmt_net_id" is the host IP address.
Please help me!!

thanks.

**Comment by richardwhiuk** [comment]
The parameters passed on heat stack-create are documented in the clearwater.yaml file - https://github.com/Metaswitch/clearwater-heat/blob/master/clearwater.yaml#L39

`public_sig_net_id` should be set the ID of the public signalling network. It should be a Neutron network ID.

`public_mgmt_net_id` should be set the ID of the public management network. It should be a Neutron network ID.

The host IP addresses come from a pool which is configured using `private_sig_net_pool_start` and `private_sig_net_pool_end` for the signalling network and `private_mgmt_net_pool_start` and `private_mgmt_net_pool_end` for the management network.

Clearwater supports having split management and signalling networks, as management traffic may contain sensitive details, and thus users may want different security and access requirements on each network.

If you don't want a split signalling and management network, you can configure the public IDs of the networks to be the same, and they will be merged to form a single network, with the signalling and management addresses on the same network.

**Comment by eleanor-merry** [comment]
Closing this as answered
